plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
    id 'maven-publish'
    id 'signing'
    id 'java-library'
}

group = 'no.sanchezrolfsen.framework'
version = '1.2.6'

repositories {
    mavenCentral()
}

ext {
    junit5Version = '5.14.4'
    seleniumVersion = '4.48.0'
    cucumberVersion = '7.34.8'
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit5Version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit5Version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit5Version"
    implementation "org.seleniumhq.selenium:selenium-api:$seleniumVersion"
    implementation "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"
    implementation "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion"
    implementation "org.seleniumhq.selenium:selenium-remote-driver:$seleniumVersion"
    implementation "org.seleniumhq.selenium:selenium-support:$seleniumVersion"
    implementation "org.seleniumhq.selenium:selenium-java:$seleniumVersion"
    implementation "io.cucumber:cucumber-core:$cucumberVersion"
    implementation "io.cucumber:cucumber-java:$cucumberVersion"
    implementation "io.cucumber:cucumber-java8:$cucumberVersion"
    implementation "io.cucumber:cucumber-junit:$cucumberVersion"
    implementation 'org.slf4j:slf4j-api:2.0.19'
    implementation 'org.apache.commons:commons-lang3:3.20.0'
    implementation 'commons-io:commons-io:2.22.0'
    implementation 'javax.ws.rs:javax.ws.rs-api:2.1.1'
    testImplementation 'org.junit.platform:junit-platform-runner:1.14.4'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:6.3.0'
}

test {
    useJUnitPlatform()
}

java {
    withSourcesJar()
    withJavadocJar()
}

/* used only for publishing
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'selenium'
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'Selenium 4 Framework with Cucumber'
                description = 'Selenium 4 Framework with cucumber 7'
                url = 'http://framework.sanchezrolfsen.no/'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://github.com/jdsk8r/selenium-cucumber-framework/blob/master/LICENSE'
                    }
                }
                developers {
                    developer {
                        id = 'diego'
                        name = 'Diego Sánchez-Rolfsen'
                        email = 'diego@sanchezrolfsen.no'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/jdsk8r/selenium-cucumber-framework.git'
                    developerConnection = 'scm:git@github.com:jdsk8r/selenium-cucumber-framework.git'
                    url = 'https://github.com/jdsk8r/selenium-cucumber-framework'
                }
            }
        }
    }
    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            def releasesRepoUrl = layout.buildDirectory.dir('repos/releases')
            def snapshotsRepoUrl = layout.buildDirectory.dir('repos/snapshots')
            url = version.endsWith('SNAPSHOT') ? 'https://s01.oss.sonatype.org/content/repositories/snapshots/' : 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/'
            credentials {
                username "$ossrhUsername"
                password "$ossrhPassword"
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}
*/

javadoc {
    if(JavaVersion.current().isJava9Compatible()) {
        options.addBooleanOption('html5', true)
    }
}
